apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      run: db-deployment
  template:
    metadata:
      labels:
        run: db-deployment
    spec:
      containers:
      - name: db-deployment
        image: postgres:9.4
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      volumes:
      - name: db-data
        emptyDir: {}