apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      run: vote-deployment
  template:
    metadata:
      labels:
        run: vote-deployment
    spec:
      containers:
      - name: vote
        image: kodekloud/examplevotingapp_vote:before