apiVersion: v1
kind: Pod
metadata:
  name: gop-file-server
  labels:
    run: gop-file-server
spec:
  containers:
  - name: gop-file-server
    image: kodekloud/fileserver
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /web
        name: data-store
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc     

