apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  labels:
    run: jekyll
spec:
  initContainers:
    - name: copy-jekyll-site
      image:  gcr.io/kodekloud/customimage/jekyll
      command: [ "jekyll", "new", "/site" ]
      volumeMounts:
      - name: site
        mountPath: /site
  containers:
    - name: jekyll
      image: gcr.io/kodekloud/customimage/jekyll-serve
      volumeMounts:
      - name: site
        mountPath: /site
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site

